
#项目地址
domain: https://www.xinmeiti3.cn/


spring:
	 #mysql
  datasource:
    url: jdbc:mysql://39.106.130.199:3306/test?useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa: 
    database: mysql
#静态资源映射  
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${file.path}
#freemarker
  freemarker: 
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .html
    template-loader-path: classpath:/templates
#redis 
  redis:
    host: 39.106.130.199
    port: 6379
    pool:
      maxActive: 8    
      maxWait: -1    
      maxIdle: 8    
      minIdle: 0    
    timeout: 0   
#tomcat Linux 端口 80
#server.port = 80
#server.port = 80
#project name
#server.context-path=/Boke
#服务器文件路径
python:
  path: ../usr/local/app/file/add.py
file: 
  path: /root/file/
#file.path=D://file/
#没用file.url=/file/**

#mybatis 缓存
mybatis:
  configuration:
    cache-enabled: true

#配置SSL证书
server:
  port: 443
  ssl:
    key-store: classpath:/1530729138824.pfx
    key-store-password: 1530729138824
    keyStoreType: PKCS12
 